<a href="https://colab.research.google.com/github/iterat1on/class/blob/main/HW1_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## HW 1 
Answer folloing questions using tensorflow's gradient tape.  

EX)
```
input_var = tf.Variable(initial_value=3.)
with tf.GradientTape() as tape:
   result = tf.square(input_var)
gradient = tape.gradient(result, input_var)
```

### Q1 Differentiate $y = x^2 + 3x + 1$ with respect to a scalar variable $x$.

In [ ]:
import tensorflow as tf

In [ ]:
# let initial value = 1
x = tf.Variable(initial_value=1.)
with tf.GradientTape() as tape :
  y = x**2+3*x+1
gr_y_wrt_x = tape.gradient(y, x)
gr_y_wrt_x

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

### Q2 Differentiate $y = X^3 + 3X + 5$ with respect to a 2 by 2 matrix variable $X$.

In [ ]:
X = tf.Variable(tf.ones((2, 2)))
with tf.GradientTape() as tape :
  y = X**3+3*X+5
gr_y_wrt_X = tape.gradient(y ,X)
gr_y_wrt_X

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[6., 6.],
       [6., 6.]], dtype=float32)>

### Q3 Differentiate $z = X^3 y^2 + 3X + 2Xy + 1$ with respect to a 2 by 2 matrix variable $X$ and a scalar variable $y$.

In [ ]:
X = tf.Variable(tf.random.uniform((2,2)))
y = tf.Variable(2.)

with tf.GradientTape(persistent=True) as tape :
  z = X**3*y**2+3*X+2*X*y+1

gr = tape.gradient(z, [X, y])
print(f'dz/dX = {gr[0]}\n \ndz/dy = {gr[1]}')

dz/dX = [[8.678173  3.005645 ]
 [8.681045  3.3938298]]
 
dz/dy = 26.628751754760742


In [ ]:
X = tf.Variable(tf.random.uniform((2,2)))
y = tf.Variable(2.)

with tf.GradientTape(persistent=True) as tape :
  z = X**3*y**2+3*X+2*X*y+1

gr = tape.gradient(z, [X, y])
print(f'dz/dX = {gr[0]}\n \ndz/dy = {gr[1]}')

dz/dX = [[7.244041 7.360065]
 [8.368526 8.490388]]
 
dz/dy = 2.3734240531921387
